name: Manual Remote Config ON

on:
  workflow_dispatch:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: "./serviceAccountReview.json"
  SERVICE_ACCOUNT_JSON: ${{ secrets.REVIEW_SERVICE_ACCOUNT_JSON }}
jobs:
  remote-config-setting-on:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: ./scripts/remoteConfigAPI/yarn.lock

      - name: Install node_modules
        run: yarn install
        working-directory: ./scripts/remoteConfigAPI

      - name: Create serviceAccount.json file
        run: echo $SERVICE_ACCOUNT_JSON | base64 --decode -i > ./serviceAccountReview.json
        working-directory: ./scripts/remoteConfigAPI

      - name: maintenance on
        run: yarn on
        working-directory: ./scripts/remoteConfigAPI
